theme:
  name: material
  language: 'zh'
  logo: logo.ico
  favicon: logo.ico
  font:
    text: 'SF'
    code: 'SF Mono'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中


plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search

nav:
  - 主页: 
    - index.md

  - 刷题:
    - 递推:
      - 刷题/递推/PAT A1093_CountPATs.md
      - 刷题/递推/PAT A1001_Quick Sort.md
    - 质数:
      - 刷题/质数/PAT A1059_Prime Factors.md
      - 刷题/质数/PAT B1013_数素数.md
    - 字符串处理:
      - 刷题/字符串处理/PAT A1060_Are They Equal.md
    - 链表:
      - 刷题/链表/PAT A1032_Sharing.md
      - 刷题/链表/PAT A1052_Linked List Sorting.md
    - 二叉树:
      - 刷题/二叉树/PAT A1020_Tree Traversals.md
    - DFS:
      - 刷题/DFS/PAT A1053_Path of Equal Weight.md
  
  - 深度学习:
    - 人工智能/index.md
  
  - 语言:
    - 语言/index.md
    - C++:
      - IO类:
        - 语言/C++/IO类/string流/1.md
        - 语言/C++/IO类/格式控制/1.md

  - 零散知识:
    - 写在前面: 零散知识/index.md
    - ELF文件: 零散知识/ELF文件/1.md
    - Raft算法: 零散知识/Raft算法/1.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition                                   # 注解块支持
  - pymdownx.arithmatex                          # 数学公式的TeX语法支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:                              # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:                           # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - meta                                         # 元数据支持

site_name: 凉白开的笔记本
site_url: https://liangbaikai1126.github.io/
repo_name: liangbaikai1126/凉白开的笔记本
repo_url: https://github.com/liangbaikai1126/liangbaikai1126.github.io
extra_css:
  - stylesheets/extra.css