theme:
  name: material
  language: 'zh'
  logo: logo.ico
  favicon: logo.ico
  font:
    text: 'Bitter'
    code: 'Cascadia Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue # 上方的
      accent: blue # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/brightness-4 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/brightness-7
        name: 切换至日间模式
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中


plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - rss

nav:
  - 主页: 
    - index.md

  - 刷题:
    - 刷题/index.md
    - 动态规划:
      - 0-1背包:
        - 刷题/动态规划/0-1背包/PAT A1068_Find More Coins.md
      - 区间DP:
        - 刷题/动态规划/区间DP/LeetCode 516.最长回文子序列.md
        - 刷题/动态规划/区间DP/LeetCode 1039.多边形三角剖分的最低得分.md
        - 刷题/动态规划/区间DP/LeetCode 5.最长回文子串.md
        - 刷题/动态规划/区间DP/PAT A1040_Longest Symmetric String.md
      - 线性DP:
        - 最大连续子序列和:
          - 刷题/动态规划/线性DP/最大连续子序列和/PAT A1007_Maximum Subsequence Sum.md
        - 最长不下降子序列LIS:
          - 刷题/动态规划/线性DP/最长不下降子序列LIS/PAT A1045_Favorite Color Stripe.md
        - 最长公共子序列LCS:
          - 刷题/动态规划/线性DP/最长公共子序列LCS/PAT A1045_Favorite Color Stripe.md
          - 刷题/动态规划/线性DP/最长公共子序列LCS/LeetCode 72.编辑距离.md
    - 图:
      - 图的遍历:
        - 刷题/图/图的遍历/PAT A1013_Battle Over Cities.md
        - 刷题/图/图的遍历/PAT A1021_Deepest Root.md
        - 刷题/图/图的遍历/PAT A1034_Head of a Gang.md
        - 刷题/图/图的遍历/PAT A1076_Forwards on Weibo.md
      - 最短路径:
        - 刷题/图/最短路径/PAT A1003_Emergency.md
        - 刷题/图/最短路径/PAT A1018_Public Bike Management.md
        - 刷题/图/最短路径/PAT A1030_Travel Plan.md
        - 刷题/图/最短路径/PAT A1072_Gas Station.md
        - 刷题/图/最短路径/PAT A1087_All Roads Lead to Rome.md
    - 堆:
      - 刷题/堆/PAT A1098_Insertion or Heap Sort.md
    - 并查集:
      - 刷题/并查集/PAT A1107_Social Clusters.md
    - 递推:
      - 刷题/递推/PAT A1093_CountPATs.md
      - 刷题/递推/PAT A1001_Quick Sort.md
    - 质数:
      - 刷题/质数/PAT A1059_Prime Factors.md
      - 刷题/质数/PAT B1013_数素数.md
    - 字符串处理:
      - 刷题/字符串处理/PAT A1060_Are They Equal.md
      - 刷题/字符串处理/PAT A1005_Spell It Right.md
    - 链表:
      - 反转链表:
        - 刷题/链表/反转链表/PAT A1074_Reversing Linked List.md
        - 刷题/链表/反转链表/LeetCode 25.K个一组反转链表.md
      - 刷题/链表/PAT A1032_Sharing.md
      - 刷题/链表/PAT A1052_Linked List Sorting.md
      - 刷题/链表/PAT A1097_Deduplication on a Linked List.md
    - 树:
      - 二叉树的遍历:
        - 刷题/树/二叉树的遍历/PAT A1020_Tree Traversals.md
        - 刷题/树/二叉树的遍历/PAT A1086_Tree Traversals Again.md
        - 刷题/树/二叉树的遍历/PAT A1102_Invert a Binary Tree.md
      - 树的遍历:
        - 刷题/树/树的遍历/PAT A1079_Total Sales of Supply Chain.md
        - 刷题/树/树的遍历/PAT A1090_Highest Price in Supply Chain.md
        - 刷题/树/树的遍历/PAT A1094_The Largest Generation.md
        - 刷题/树/树的遍历/PAT A1106_Lowest Price in Supply Chain.md
        - 刷题/树/树的遍历/PAT A1004_Counting Leaves.md
        - 刷题/树/树的遍历/PAT A1053_Path of Equal Weight.md
      - 二叉查找树:
        - 刷题/树/二叉查找树/PAT A1043_Is it a Binary Search Tree.md
        - 刷题/树/二叉查找树/PAT A1064_Complete Binary Search Tree.md
        - 刷题/树/二叉查找树/PAT A1099_Build a Binary Search Tree.md
      - 平衡二叉树:
        - 刷题/树/平衡二叉树/PAT A1066_Root of AVL Tree.md
    - DFS:
      - 刷题/DFS/PAT A1103_Integer Factorization.md
    - BFS:
      - 刷题/BFS/PAT A1091_Acute Stroke.md
    - 栈:
      - 刷题/栈/PAT A1051_Pop Sequence.md
    - 队列:
      - 刷题/队列/PAT A1056_Mice and Rice.md
    - 模拟:
      - 刷题/模拟/PAT A1006_Sign In and Sign Out.md
      - 刷题/模拟/PAT A1008_Elevator.md
      - 刷题/模拟/PAT A1001_A+B Format.md
      - 刷题/模拟/PAT A1002_A+B for Polynomials.md
      - 刷题/模拟/PAT A1009_Product of Polynomials.md
      - 刷题/模拟/PAT A1042_Shuffing Machine.md
      - 刷题/模拟/PAT A1046_Shortest Distance.md
      - 刷题/模拟/PAT A1065_A+B and C (64bit).md
      - 刷题/模拟/PAT A1011_World Cup Betting.md
      - 刷题/模拟/PAT A1036_Boys vs Girls.md
      - 刷题/模拟/PAT A1031_Hello World for U.md
      - 刷题/模拟/PAT A1019_General Palindromic Number.md
      - 刷题/模拟/PAT A1027_Colors in Mars.md
      - 刷题/模拟/PAT A1058_A+B in Hogwarts.md
      - 刷题/模拟/PAT A1073_Scientific Notation.md
      - 刷题/模拟/PAT A1035_Password.md
      - 刷题/模拟/PAT A1077_Kuchiguse.md
      - 刷题/模拟/PAT A1082_Read Number in Chinese.md
      - 刷题/模拟/PAT A1061_Dating.md
    - 二分查找:
      - 刷题/二分查找/PAT A1010_Radix.md
    - 排序:
      - 刷题/排序/PAT A1062_Talent and Virtue.md
      - 刷题/排序/PAT A1012_The Best Rank.md
      - 刷题/排序/PAT A1016_Phone Bills.md
      - 刷题/排序/PAT A1025_PAT Ranking.md
      - 刷题/排序/PAT A1028_List Sorting.md
      - 刷题/排序/PAT A1055_The World's Richest.md
      - 刷题/排序/PAT A1075_PAT Judge.md
      - 刷题/排序/PAT A1083_List Grades.md
      - 刷题/排序/PAT A1080_Graduate Admission.md
      - 刷题/排序/PAT A1095_Cars on Campus.md
    - 散列:
      - 刷题/散列/PAT A1084_Broken Keyboard.md
      - 刷题/散列/PAT A1092_To Buy or Not to Buy.md
      - 刷题/散列/PAT A1041_Be Unique.md
      - 刷题/散列/PAT A1050_String Subtraction.md
      - 刷题/散列/PAT A1048_Find Coins.md
    - 贪心:
      - 刷题/贪心/PAT A1070_Mooncake.md
      - 刷题/贪心/PAT A1033_To Fill or Not to Fill.md
      - 刷题/贪心/LeetCode 3216.交换后字典序最小的字符串.md
      - 刷题/贪心/LeetCode 670.最大交换.md
  - 图形学:
    - GAMES101:
      - 图形学/GAMES101/index.md
      - 图形学/GAMES101/Lec02/1.md
      - 图形学/GAMES101/Lec03/1.md
      - 图形学/GAMES101/Lec04/1.md
    - GAMES102:
      - 图形学/GAMES102/index.md
      - 图形学/GAMES102/Lec05/1.md
  
  - 语言:
    - 语言/index.md
    - C++:
      - 语言/C++/string流/1.md
      - 语言/C++/格式控制/1.md
      - 语言/C++/报错相关/1.md
    - Python:
      - 语言/Python/字符串和字符列表/1.md
    - 日语:
      - 语言/日语/初级第1课.md
      - 语言/日语/初级第2课.md
      - 语言/日语/初级第3课.md
      - 语言/日语/初级第4课.md
      - 语言/日语/初级第5课.md
      - 语言/日语/初级第6课.md
      - 语言/日语/初级第7课.md
      - 语言/日语/初级第8课.md
      - 语言/日语/初级第9课.md
      - 语言/日语/初级第10课.md
      - 语言/日语/初级第11课.md
      - 语言/日语/初级第12课.md
      - 语言/日语/初级第13课.md
      - 语言/日语/初级第14课.md
      - 语言/日语/初级第15课.md
      - 语言/日语/动词变形之て形、た形.md
      - 语言/日语/动词三分类.md

  - 其他:
    - 写在前面: 其他/index.md
    - WSL安装教程: 其他/Win11家庭版配置WSL2/1.md
    - Git相关问题: 其他/Git相关/1.md
    - Conda相关问题: 其他/Conda相关/1.md
    - psbody安装: 其他/psbody安装/1.md
    - WSL2终端代理配置Clash: 其他/WSL2终端代理配置Clash/1.md
    - 使用OCC编写脚本: 其他/使用OCC编写脚本/1.md

markdown_extensions:
  - toc:
      permalink: true                                # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition                                       # 注解块支持
  - pymdownx.arithmatex:                             # 数学公式的TeX语法支持
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:                                  # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:                               # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - meta                                             # 元数据支持
  - attr_list # 按钮 / 图片
  - pymdownx.snippets # 术语 / 代码块         

extra_javascript:
  - javascripts/katex.js
  - javascripts/extra.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css


site_name: 开的博客
site_url: https://liangbaikai1126.github.io/
repo_name: liangbaikai1126/开的博客
repo_url: https://github.com/liangbaikai1126/liangbaikai1126.github.io